### NHTSA Data Process

In [12]:
import pandas as pd

In [13]:
fields = pd.read_excel('fields.xlsx')
fields

,Field#,Name,Type/Size,Description
0,1,CMPLID,CHAR(9),NHTSA'S INTERNAL UNIQUE SEQUENCE NUMBER. IS AN...
1,2,ODINO,CHAR(9),NHTSA'S INTERNAL REFERENCE NUMBER. THIS NUMBER...
2,3,MFR_NAME,CHAR(40),MANUFACTURER'S NAME
3,4,MAKETXT,CHAR(25),VEHICLE/EQUIPMENT MAKE
4,5,MODELTXT,CHAR(256),VEHICLE/EQUIPMENT MODEL
5,6,YEARTXT,CHAR(4),"MODEL YEAR, 9999 IF UNKNOWN or N/A"
6,7,CRASH,CHAR(1),"WAS VEHICLE INVOLVED IN A CRASH, 'Y' OR 'N'"
7,8,FAILDATE,CHAR(8),DATE OF INCIDENT (YYYYMMDD)
8,9,FIRE,CHAR(1),WAS VEHICLE INVOLVED IN A FIRE 'Y' OR 'N'
9,10,INJURED,NUMBER(2),NUMBER OF PERSONS INJURED
10,11,DEATHS,NUMBER(2),NUMBER OF FATALITIES
11,12,COMPDESC,CHAR(128),SPECIFIC COMPONENT'S DESCRIPTION
12,13,CITY,CHAR(30),CONSUMER'S CITY
13,14,STATE,CHAR(2),CONSUMER'S STATE CODE
14,15,VIN,CHAR(11),VEHICLE'S VIN#
15,16,DATEA,CHAR(8),DATE ADDED TO FILE (YYYYMMDD)
16,17,LDATE,CHAR(8),DATE COMPLAINT RECEIVED BY NHTSA (YYYYMMDD)
17,18,MILES,NUMBER(7),VEHICLE MILEAGE AT FAILURE
18,19,OCCURENCES,NUMBER(4),NUMBER OF OCCURRENCES
19,20,CDESCR,CHAR(2048),DESCRIPTION OF THE COMPLAINT
20,21,CMPL_TYPE,CHAR(4),SOURCE OF COMPLAINT CODE: CAG =CONSUMER ACTIO...
21,22,POLICE_RPT_YN,CHAR(1),WAS INCIDENT REPORTED TO POLICE 'Y' OR 'N'
22,23,PURCH_DT,CHAR(8),DATE PURCHASED (YYYYMMDD)
23,24,ORIG_OWNER_YN,CHAR(1),WAS ORIGINAL OWNER 'Y' OR 'N'
24,25,ANTI_BRAKES_YN,CHAR(1),ANTI-LOCK BRAKES 'Y' OR 'N'
25,26,CRUISE_CONT_YN,CHAR(1),CRUISE CONTROL 'Y' OR 'N'
26,27,NUM_CYLS,NUMBER(2),NUMBER OF CYLINDERS
27,28,DRIVE_TRAIN,CHAR(4),"DRIVE TRAIN TYPE [AWD,4WD,FWD,RWD]"
28,29,FUEL_SYS,CHAR(4),FUEL SYSTEM CODE: FI =FUEL INJECTION; TB =TURBO
29,30,FUEL_TYPE,CHAR(4),FUEL TYPE CODE: BF =BIFUEL; CN =CNG/LPG; CN =C...
30,31,TRANS_TYPE,CHAR(4),"VEHICLE TRANSMISSION TYPE [AUTO, MAN]"
31,32,VEH_SPEED,NUMBER(3),VEHICLE SPEED
32,33,DOT,CHAR(20),DEPARTMENT OF TRANSPORTATION TIRE IDENTIFIER
33,34,TIRE_SIZE,CHAR(30),TIRE SIZE
34,35,LOC_OF_TIRE,CHAR(4),LOCATION OF TIRE CODE: FSW =DRIVER SIDE FRONT;...
35,36,TIRE_FAIL_TYPE,CHAR(4),TYPE OF TIRE FAILURE CODE: BST =BLISTER;BLW =B...
36,37,ORIG_EQUIP_YN,CHAR(1),WAS PART ORIGINAL EQUIPMENT 'Y' OR 'N'
37,38,MANUF_DT,CHAR(8),DATE OF MANUFACTURE (YYYYMMDD)
38,39,SEAT_TYPE,CHAR(4),TYPE OF CHILD SEAT CODE: B =BOOSTERC =CONVER...
39,40,RESTRAINT_TYPE,CHAR(4),INSTALLATION SYSTEM CODE: A =VEHICLE SAFETY BE...
40,41,DEALER_NAME,CHAR(40),DEALER'S NAME
41,42,DEALER_TEL,CHAR(20),DEALER'S TELEPHONE NUMBER
42,43,DEALER_CITY,CHAR(30),DEALER'S CITY
43,44,DEALER_STATE,CHAR(2),DEALER'S STATE CODE
44,45,DEALER_ZIP,CHAR(10),DEALER'S ZIPCODE
45,46,PROD_TYPE,CHAR(4),PRODUCT TYPE CODE: V =VEHICLE; T =TIRES; E =EQ...
46,47,REPAIRED_YN,CHAR(1),WAS DEFECTIVE TIRE REPAIRED 'Y' OR 'N'
47,48,MEDICAL_ATTN,CHAR(1),WAS MEDICAL ATTENTION REQUIRED 'Y' OR 'N'
48,49,VEHICLES_TOWED_YN,CHAR(1),WAS VEHICLE TOWED 'Y' OR 'N'

In [14]:
col_names = fields['Name'].tolist()
col_names

['CMPLID',
 'ODINO',
 'MFR_NAME',
 'MAKETXT',
 'MODELTXT',
 'YEARTXT',
 'CRASH',
 'FAILDATE',
 'FIRE',
 'INJURED',
 'DEATHS',
 'COMPDESC',
 'CITY',
 'STATE',
 'VIN',
 'DATEA',
 'LDATE',
 'MILES',
 'OCCURENCES',
 'CDESCR',
 'CMPL_TYPE',
 'POLICE_RPT_YN',
 'PURCH_DT',
 'ORIG_OWNER_YN',
 'ANTI_BRAKES_YN',
 'CRUISE_CONT_YN',
 'NUM_CYLS',
 'DRIVE_TRAIN',
 'FUEL_SYS',
 'FUEL_TYPE',
 'TRANS_TYPE',
 'VEH_SPEED',
 'DOT',
 'TIRE_SIZE',
 'LOC_OF_TIRE',
 'TIRE_FAIL_TYPE',
 'ORIG_EQUIP_YN',
 'MANUF_DT',
 'SEAT_TYPE',
 'RESTRAINT_TYPE',
 'DEALER_NAME',
 'DEALER_TEL',
 'DEALER_CITY',
 'DEALER_STATE',
 'DEALER_ZIP',
 'PROD_TYPE',
 'REPAIRED_YN',
 'MEDICAL_ATTN',
 'VEHICLES_TOWED_YN']

In [15]:
data = pd.read_csv('COMPLAINTS_RECEIVED_2020-2023.txt', sep="\t", header=None)
data

/var/folders/v4/vvv65nr17s1c23jvqd4591t80000gn/T/ipykernel_28721/3927424130.py:1: DtypeWarning: Columns (28,30,33,38,41,44) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('COMPLAINTS_RECEIVED_2020-2023.txt', sep="\t", header=None)

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
0,1633299,11292384,Honda (American Honda Motor Co.),HONDA,ACCORD,2018.0,N,20191221,N,0,...,NaN,NaN,NaN,NaN,NaN,NaN,V,NaN,N,N
1,1633300,11292384,Honda (American Honda Motor Co.),HONDA,ACCORD,2018.0,N,20191221,N,0,...,NaN,NaN,NaN,NaN,NaN,NaN,V,NaN,N,N
2,1633301,11292384,Honda (American Honda Motor Co.),HONDA,ACCORD,2018.0,N,20191221,N,0,...,NaN,NaN,NaN,NaN,NaN,NaN,V,NaN,N,N
3,1633302,11292385,Ford Motor Company,FORD,EXPLORER,2020.0,N,20191226,N,0,...,NaN,NaN,NaN,NaN,NaN,NaN,V,NaN,N,N
4,1633303,11292386,"General Motors, LLC",CHEVROLET,VOLT,2017.0,N,20190712,N,0,...,NaN,NaN,NaN,NaN,NaN,NaN,V,NaN,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235580,1868879,11504581,Hyundai Motor America,HYUNDAI,IONIQ 5,2022.0,N,20221027,N,0,...,NaN,NaN,NaN,NaN,NaN,NaN,V,NaN,N,N
235581,1868880,11504583,"Chrysler (FCA US, LLC)",CHRYSLER,TOWN AND COUNTRY,2014.0,N,20200130,N,0,...,NaN,NaN,NaN,NaN,NaN,NaN,V,NaN,N,N
235582,1868881,11504583,"Chrysler (FCA US, LLC)",CHRYSLER,TOWN AND COUNTRY,2014.0,N,20200130,N,0,...,NaN,NaN,NaN,NaN,NaN,NaN,V,NaN,N,N
235583,1868882,11504584,"General Motors, LLC",CHEVROLET,TRAILBLAZER,2022.0,N,20220910,N,0,...,NaN,NaN,NaN,NaN,NaN,NaN,V,NaN,N,N
235584,1868883,11504584,"General Motors, LLC",CHEVROLET,TRAILBLAZER,2022.0,N,20220910,N,0,...,NaN,NaN,NaN,NaN,NaN,NaN,V,NaN,N,N

In [16]:
data.columns = col_names
#data = pd.DataFrame(data, columns= col_names)
data

,CMPLID,ODINO,MFR_NAME,MAKETXT,MODELTXT,YEARTXT,CRASH,FAILDATE,FIRE,INJURED,...,RESTRAINT_TYPE,DEALER_NAME,DEALER_TEL,DEALER_CITY,DEALER_STATE,DEALER_ZIP,PROD_TYPE,REPAIRED_YN,MEDICAL_ATTN,VEHICLES_TOWED_YN
0,1633299,11292384,Honda (American Honda Motor Co.),HONDA,ACCORD,2018.0,N,20191221,N,0,...,NaN,NaN,NaN,NaN,NaN,NaN,V,NaN,N,N
1,1633300,11292384,Honda (American Honda Motor Co.),HONDA,ACCORD,2018.0,N,20191221,N,0,...,NaN,NaN,NaN,NaN,NaN,NaN,V,NaN,N,N
2,1633301,11292384,Honda (American Honda Motor Co.),HONDA,ACCORD,2018.0,N,20191221,N,0,...,NaN,NaN,NaN,NaN,NaN,NaN,V,NaN,N,N
3,1633302,11292385,Ford Motor Company,FORD,EXPLORER,2020.0,N,20191226,N,0,...,NaN,NaN,NaN,NaN,NaN,NaN,V,NaN,N,N
4,1633303,11292386,"General Motors, LLC",CHEVROLET,VOLT,2017.0,N,20190712,N,0,...,NaN,NaN,NaN,NaN,NaN,NaN,V,NaN,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235580,1868879,11504581,Hyundai Motor America,HYUNDAI,IONIQ 5,2022.0,N,20221027,N,0,...,NaN,NaN,NaN,NaN,NaN,NaN,V,NaN,N,N
235581,1868880,11504583,"Chrysler (FCA US, LLC)",CHRYSLER,TOWN AND COUNTRY,2014.0,N,20200130,N,0,...,NaN,NaN,NaN,NaN,NaN,NaN,V,NaN,N,N
235582,1868881,11504583,"Chrysler (FCA US, LLC)",CHRYSLER,TOWN AND COUNTRY,2014.0,N,20200130,N,0,...,NaN,NaN,NaN,NaN,NaN,NaN,V,NaN,N,N
235583,1868882,11504584,"General Motors, LLC",CHEVROLET,TRAILBLAZER,2022.0,N,20220910,N,0,...,NaN,NaN,NaN,NaN,NaN,NaN,V,NaN,N,N
235584,1868883,11504584,"General Motors, LLC",CHEVROLET,TRAILBLAZER,2022.0,N,20220910,N,0,...,NaN,NaN,NaN,NaN,NaN,NaN,V,NaN,N,N

In [17]:
com_des_df = data[['COMPDESC', 'CDESCR']]
com_des_df

,COMPDESC,CDESCR
0,SERVICE BRAKES,"DRIVING AT THE HIGHWAY, CAR SUDDENLY SLOW DOWN..."
1,ELECTRICAL SYSTEM,"DRIVING AT THE HIGHWAY, CAR SUDDENLY SLOW DOWN..."
2,ENGINE,"DRIVING AT THE HIGHWAY, CAR SUDDENLY SLOW DOWN..."
3,ELECTRICAL SYSTEM,DEEP SLEEP MODE ACTIVATES AFTER 2 DAYS. MOST ...
4,SERVICE BRAKES,"WHILE DRIVING ON CITY STREETS AND HIGHWAYS, TH..."
...,...,...
235580,ELECTRICAL SYSTEM,The car randomly drains the 12v battery. Twice...
235581,SEATS,The safety feature of the front row headrest r...
235582,AIR BAGS,The safety feature of the front row headrest r...
235583,SERVICE BRAKES,"2022 Trailblazer with approximately 21,000 mil..."
235584,FORWARD COLLISION AVOIDANCE: ADAPTIVE CRUISE C...,"2022 Trailblazer with approximately 21,000 mil..."

In [18]:
com_des_df = com_des_df.drop_duplicates()
com_des_df

,COMPDESC,CDESCR
0,SERVICE BRAKES,"DRIVING AT THE HIGHWAY, CAR SUDDENLY SLOW DOWN..."
1,ELECTRICAL SYSTEM,"DRIVING AT THE HIGHWAY, CAR SUDDENLY SLOW DOWN..."
2,ENGINE,"DRIVING AT THE HIGHWAY, CAR SUDDENLY SLOW DOWN..."
3,ELECTRICAL SYSTEM,DEEP SLEEP MODE ACTIVATES AFTER 2 DAYS. MOST ...
4,SERVICE BRAKES,"WHILE DRIVING ON CITY STREETS AND HIGHWAYS, TH..."
...,...,...
235580,ELECTRICAL SYSTEM,The car randomly drains the 12v battery. Twice...
235581,SEATS,The safety feature of the front row headrest r...
235582,AIR BAGS,The safety feature of the front row headrest r...
235583,SERVICE BRAKES,"2022 Trailblazer with approximately 21,000 mil..."
235584,FORWARD COLLISION AVOIDANCE: ADAPTIVE CRUISE C...,"2022 Trailblazer with approximately 21,000 mil..."

In [19]:
com_des_df = com_des_df.apply(lambda x: x.astype(str).str.lower()).sample(n=100)
com_des_df

,COMPDESC,CDESCR
143924,steering,the contact owns a 2018 honda civic. the conta...
219311,power train,hi i have ford focus sel 2017 which i bought i...
20290,suspension,the car has problems starting up. the starter ...
106724,power train,"bought hyundai sante fe sport 2017 36,871 mile..."
70003,service brakes,tl* the contact owns a 2002 lincoln blackwood....
...,...,...
84514,suspension,tl* the contact owns a 2016 ford explorer. the...
58980,vehicle speed control,"i was driving on the freeway, as i had acceler..."
30830,engine,the car started to make a soft ticking sound. ...
9342,electrical system,"my truck will not start, it won't even turn on..."
41530,power train,the air conditioning had stopped blowing cool ...

In [20]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(com_des_df, test_size=0.2)

In [21]:
train['CDESCR'].to_csv('train.txt', sep="\n", index=False, header=None)

In [25]:
test

,COMPDESC,CDESCR
67634,fuel/propulsion system,it takes half an hour to fill my tank it keeps...
173805,visibility/wiper,windshield separation from body of car causing...
187191,visibility/wiper,it started to rain and my windshield wipers st...
28708,"fuel system, gasoline",tl* the contact owns a 2018 toyota tacoma. the...
146046,seats,the back of the seat does not stay secured in ...
101813,structure:body,"on two occasions, one stationary, one in motio..."
46824,engine,car loses power while in the middle of driving...
1593,vehicle speed control,on 10 aug 2019 i took my ford in for transmiss...
157288,electrical system,battery 620 cca. batter is 28 months old. ins...
38557,equipment adaptive/mobility,recently i parked my vehicle on my apartment p...
38453,exterior lighting,wiring in headlight assemblies shorts out beca...
106724,power train,"bought hyundai sante fe sport 2017 36,871 mile..."
30147,air bags,passenger side head rest - headrest deployed w...
179356,fuel/propulsion system,"while driving, vehicle has abruptly stopped/en..."
99056,air bags,tl* takata recall. the contact owns a 2014 gmc...
199064,"service brakes, hydraulic",the contact owns a 2021 ford bronco sport. the...
108278,steering,"ford explorer 2015 4wd (79,000 km), currently ..."
175942,engine and engine cooling,the contact owns a 2016 kia soul. the contact ...
4222,unknown or other,my passenger sliding door in a permanent locke...
62295,tires:sidewall,purchased 4 brand new lexani thirty tires with...

In [26]:
test.to_csv('test.csv', index=False, header=['sent1', 'sent0'])

### Unspervised

In [ ]:
# import torch
# from scipy.spatial.distance import cosine
# from transformers import AutoModel, AutoTokenizer

# # Import our models. The package will take care of downloading the models automatically
# tokenizer = AutoTokenizer.from_pretrained("princeton-nlp/unsup-simcse-bert-base-uncased")
# model = AutoModel.from_pretrained("princeton-nlp/unsup-simcse-bert-base-uncased")

# # Tokenize input texts
# train = train.tolist()
# inputs = tokenizer(train, padding=True, truncation=True, return_tensors="pt")

# # Get the embeddings
# with torch.no_grad():
#     embeddings = model(**inputs, output_hidden_states=True, return_dict=True).pooler_output

# # Calculate cosine similarities
# # Cosine similarities are in [-1, 1]. Higher means more similar
# cosine_sim_0_1 = 1 - cosine(embeddings[0], embeddings[1])
# cosine_sim_0_2 = 1 - cosine(embeddings[0], embeddings[2])

# print("Cosine similarity between \"%s\" and \"%s\" is: %.3f" % (texts[0], texts[1], cosine_sim_0_1))
# print("Cosine similarity between \"%s\" and \"%s\" is: %.3f" % (texts[0], texts[2], cosine_sim_0_2))